### ISSUE TITLE
feat(`parseFunctionDeclaration`): improve formatting detection

### ISSUE THREAD

**Issue by tcoratger** [grindery-io/grindery-nexus-connector-web3#106]
In the regex that dispatches the different parts of the function signature, it doesn't need to have the `function` prefix at the start at the moment. This can lead to inconsistencies.

For example, if by mistake, the name of the function is forgotten, this would cause a signature of type `function (bytes32 args, bytes32 r, bytes32 s) external;`. In this case, the parser would understand that `function` is the name of the function, which of course leads to inconsistency and the impossibility of calling this function because it does not exist.

So I suggest that the `function` prefix be mandatory (it could also be totally removed, but it's mostly present and it adds more meaning in the signature writing) at the beginning. In this way there can be no ambiguity. And if the `function` prefix is not present then the `Invalid function declaration` error is thrown.

Similar to #103 but related to function signature.

**Comment by SAPikachu** [comment]
@tcoratger I think it would be a better idea to keep this because:

1. I don't remember where but I am afraid that some components already depend on the no-function format, fixing this will break them.
2. Additionally, I also don't think this error is likely, as function name is very important and not at the beginning of the signature, it is hard to imagine how it can be missed. :)

I do understand that it is a good idea to prevent this issue, I would suggest to add another regex check to detect and reject this (Something like `^\s*function\s*\(`), in this way we can avoid the issue and keep the old behavior. What do you think?

**Comment by tcoratger** [comment]
@SAPikachu Agreed, @juniormp can you handle this in both #109 and #110? as well as adding the corresponding unit tests to verify that it is indeed impossible to have `function (bytes32 offerId, address destAddress, uint256 amountOffer) external payable returns (bytes32)` or `event (bytes32 indexed _offerId, address indexed _token, uint256 _chainId);`?
